description: "Just another Engineering student's blog"
baseurl: ""
url: "https://augurcognito.live/"
title_description: I am doing my bachelors in Electronics & Telecommunication. Here I post stuff related to technology and programming, or whatever stuff i find interesting.
title_image: "https://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
google_analytics: 
disqus_account: aug# Site settings
title: "Aniket Singh"
email: singhaniket@tutanota.com
disqus_account: augurcognito
github_repository: https://github.com/AugurCognito/blog
addthis_id:
plausible_site:
goatcounter_code:
cloudflare_toekn: 901c82e8d7b04dbcaf5070740094c2eb
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  AugurCognito
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/aniket-singh-aa6314203/
stackoverflow_link: 
xing_link:
facebook_link:
lastfm_username: aniketchahal

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://keybase.io/augurcognito\">Aniket Singh</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/AugurCognito/blog\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    # block:
    #   line_numbers: true
    #   start_line: 1
  
jekyll-spaceship:
  # default enabled processors
  processors:
    - table-processor
    - mathjax-processor
    - plantuml-processor
    - mermaid-processor
    - polyfill-processor
    - media-processor
    - emoji-processor
    - element-processor
  mathjax-processor:
    src:
      - https://polyfill.io/v3/polyfill.min.js?features=es6
      - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    config:
      tex:
        inlineMath:
          - ['$','$']
          - ['\(','\)']
        displayMath:
          - ['$$','$$']
          - ['\[','\]']
      svg:
        fontCache: 'global'
    optimize: # optimization on building stage to check and add mathjax scripts
      enabled: true # value `false` for adding to all pages
      include: []   # include patterns for math expressions checking (regexp)
      exclude: []   # exclude patterns for math expressions checking (regexp)
  plantuml-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: plantuml
    syntax:
      code: 'plantuml!'
      custom: ['@startuml', '@enduml']
    src: http://www.plantuml.com/plantuml/svg/
  mermaid-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: mermaid
    syntax:
      code: 'mermaid!'
      custom: ['@startmermaid', '@endmermaid']
    config:
      theme: dark


permalink: pretty
exclude: [vendor]
plugins:
  - jekyll-spaceship
