# Site settings
title: "Aniket Singh"
email: singhaniket@tutanota.com
description: "Just another Engineering student's blog"
baseurl: ""
url: "https://augurcognito.live/"
title_description: I am doing my bachelors in Electronics & Telecommunication. Here I post stuff related to technology and programming, or whatever stuff i find intresting.
title_image: "https://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
google_analytics: 
disqus_account: augurcognito
github_repository: https://github.com/AugurCognito/blog
addthis_id:
plausible_site: augurcognito.live
goatcounter_code: augurcognito
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  AugurCognito
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/aniket-singh-aa6314203/
stackoverflow_link: 
xing_link:
facebook_link:
lastfm_username: aniketchahal

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://keybase.io/augurcognito\">Aniket Singh</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/AugurCognito/blog\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    # block:
    #   line_numbers: true
    #   start_line: 1
  
  

permalink: pretty
exclude: [vendor]
